export type HiringFunction = "Product" | "Design" | "Engineering";

export type RemoteCompany = {
  company: string;
  hiringFor: HiringFunction[];
  exampleRole: string;
  careersUrl: string;
  sourceLabel: string;
};

export const remoteUsHiringCompanies: RemoteCompany[] = [
  {
    company: "ABBYY",
    hiringFor: ["Product", "Design"],
    exampleRole: "Staff Product Designer",
    careersUrl: "https://boards.greenhouse.io/embed/job_app?token=4643977101",
    sourceLabel: "Greenhouse",
  },
  {
    company: "Agiloft",
    hiringFor: ["Engineering"],
    exampleRole: "Senior Fullstack Developer (Agentic AI)",
    careersUrl: "https://jobs.lever.co/agiloft/5380449b-f68d-4124-b399-2a42e0fdcd8a",
    sourceLabel: "Lever",
  },
  {
    company: "Aledade",
    hiringFor: ["Product"],
    exampleRole: "Technical Product Manager - AI Platform",
    careersUrl: "https://jobs.lever.co/aledade/2bd8ba8a-2a92-443e-9638-2a08a7da0fb4",
    sourceLabel: "Lever",
  },
  {
    company: "Anchorage Digital",
    hiringFor: ["Product", "Design", "Engineering"],
    exampleRole: "Member of Product Design, Digital Assets",
    careersUrl: "https://jobs.lever.co/anchorage/?location=United+States",
    sourceLabel: "Lever",
  },
  {
    company: "Apollo.io",
    hiringFor: ["Design"],
    exampleRole: "Senior Product Designer, CRM",
    careersUrl: "https://boards.greenhouse.io/embed/job_app?token=5577759004",
    sourceLabel: "Greenhouse",
  },
  {
    company: "Articulate",
    hiringFor: ["Product", "Design", "Engineering"],
    exampleRole: "Senior Product Manager (AI Media)",
    careersUrl: "https://jobs.lever.co/articulate?location=United+States",
    sourceLabel: "Lever",
  },
  {
    company: "Aura",
    hiringFor: ["Product"],
    exampleRole: "Senior AI Product Manager",
    careersUrl: "https://boards.greenhouse.io/embed/job_app?token=5539148004",
    sourceLabel: "Greenhouse",
  },
  {
    company: "Bluesight",
    hiringFor: ["Engineering"],
    exampleRole: "Full Stack Software Engineer - 340B Check",
    careersUrl: "https://jobs.lever.co/bluesight/0a804012-b29d-4591-b2c5-03dab485675d",
    sourceLabel: "Lever",
  },
  {
    company: "Cyderes",
    hiringFor: ["Design"],
    exampleRole: "Director, Product Design",
    careersUrl: "https://jobs.lever.co/cyderes/fcff17e2-e3bd-45e3-966c-eca6ad0c5814",
    sourceLabel: "Lever",
  },
  {
    company: "Datavant",
    hiringFor: ["Product"],
    exampleRole: "Staff Product Manager, Legal & Insurance",
    careersUrl: "https://boards.greenhouse.io/embed/job_app?for=datavant2&token=4918772008",
    sourceLabel: "Greenhouse",
  },
  {
    company: "Egen",
    hiringFor: ["Engineering"],
    exampleRole: "Lead Engineer",
    careersUrl: "https://jobs.lever.co/egen/1b8ed5c2-baad-4820-80bd-c755fb9f65d9",
    sourceLabel: "Lever",
  },
  {
    company: "Ellevation",
    hiringFor: ["Design"],
    exampleRole: "Senior Product Designer",
    careersUrl: "https://jobs.lever.co/ellevationeducation/a4f9bcde-01c4-4d1a-8cc5-007ca81dcf1e",
    sourceLabel: "Lever",
  },
  {
    company: "Eventbrite",
    hiringFor: ["Design", "Engineering"],
    exampleRole: "Staff Product Designer",
    careersUrl: "https://boards.greenhouse.io/embed/job_app?token=4679035007",
    sourceLabel: "Greenhouse",
  },
  {
    company: "Everbridge",
    hiringFor: ["Product"],
    exampleRole: "Principal Product Manager, Risk Intelligence",
    careersUrl: "https://jobs.lever.co/everbridge/7a484eac-45bd-4b7f-9cf6-335c71d1fd62",
    sourceLabel: "Lever",
  },
  {
    company: "Everlywell",
    hiringFor: ["Design"],
    exampleRole: "Visual Senior Product Designer",
    careersUrl: "https://jobs.lever.co/everlywell/7b7ac528-ec42-4480-b1fd-11ded686380e",
    sourceLabel: "Lever",
  },
  {
    company: "Fictiv",
    hiringFor: ["Engineering"],
    exampleRole: "Senior Software Engineer (Remote - US)",
    careersUrl: "https://boards.greenhouse.io/embed/job_app?token=8186077002",
    sourceLabel: "Greenhouse",
  },
  {
    company: "Getlabs",
    hiringFor: ["Design"],
    exampleRole: "Product Designer - UX/UI",
    careersUrl: "https://jobs.lever.co/getlabs/b83888d4-5a0d-4c16-a828-2e1079eab171",
    sourceLabel: "Lever",
  },
  {
    company: "Harbor",
    hiringFor: ["Product"],
    exampleRole: "Product Manager, Legal Technical Systems",
    careersUrl: "https://boards.greenhouse.io/embed/job_app?token=4810650007",
    sourceLabel: "Greenhouse",
  },
  {
    company: "Headspace",
    hiringFor: ["Engineering"],
    exampleRole: "Senior Software Engineer, Flutter",
    careersUrl: "https://boards.greenhouse.io/embed/job_app?token=7206177",
    sourceLabel: "Greenhouse",
  },
  {
    company: "HubSpot",
    hiringFor: ["Design"],
    exampleRole: "Senior Product Designer II, Developer Product Group",
    careersUrl: "https://boards.greenhouse.io/embed/job_app?token=7195609",
    sourceLabel: "Greenhouse",
  },
  {
    company: "Legion",
    hiringFor: ["Engineering"],
    exampleRole: "Director of Engineering, Cloud Application Platform",
    careersUrl: "https://boards.greenhouse.io/embed/job_app?token=7189866003",
    sourceLabel: "Greenhouse",
  },
  {
    company: "Lumin Digital",
    hiringFor: ["Design"],
    exampleRole: "Senior Product Designer",
    careersUrl: "https://jobs.lever.co/LuminDigital/d769e148-1ecc-45c1-8ef9-083993f28142",
    sourceLabel: "Lever",
  },
  {
    company: "Luxury Presence",
    hiringFor: ["Product", "Design", "Engineering"],
    exampleRole: "Staff Product Designer - US (Remote)",
    careersUrl: "https://jobs.lever.co/luxurypresence?workplaceType=remote",
    sourceLabel: "Lever",
  },
  {
    company: "Nava",
    hiringFor: ["Design"],
    exampleRole: "Senior Product Designer",
    careersUrl: "https://boards.greenhouse.io/embed/job_app?token=6690915003",
    sourceLabel: "Greenhouse",
  },
  {
    company: "Nebius",
    hiringFor: ["Engineering"],
    exampleRole: "Senior Software Engineer — AI Studio (Inference Platform)",
    careersUrl: "https://boards.greenhouse.io/embed/job_app?token=4600912101",
    sourceLabel: "Greenhouse",
  },
  {
    company: "Nextech",
    hiringFor: ["Product", "Engineering"],
    exampleRole: "Senior Product Manager - Healthcare Patient Experience",
    careersUrl: "https://jobs.lever.co/nextech/",
    sourceLabel: "Lever",
  },
  {
    company: "Omada Health",
    hiringFor: ["Product"],
    exampleRole: "Product Manager, Enterprise",
    careersUrl: "https://boards.greenhouse.io/embed/job_app?token=7246354",
    sourceLabel: "Greenhouse",
  },
  {
    company: "PagerDuty",
    hiringFor: ["Product"],
    exampleRole: "Principal Product Manager, Growth",
    careersUrl: "https://boards.greenhouse.io/embed/job_app?token=5611408004",
    sourceLabel: "Greenhouse",
  },
  {
    company: "Pair Team",
    hiringFor: ["Product"],
    exampleRole: "Principal Product Manager",
    careersUrl: "https://boards.greenhouse.io/embed/job_app?token=8068409002",
    sourceLabel: "Greenhouse",
  },
  {
    company: "Palmetto",
    hiringFor: ["Product"],
    exampleRole: "Product Manager, Lifecycle Engagement & Comms",
    careersUrl: "https://boards.greenhouse.io/embed/job_app?token=4821380008",
    sourceLabel: "Greenhouse",
  },
  {
    company: "Parallel",
    hiringFor: ["Design"],
    exampleRole: "Senior Product Designer",
    careersUrl: "https://boards.greenhouse.io/embed/job_app?token=4580000005",
    sourceLabel: "Greenhouse",
  },
  {
    company: "Precision Medicine Group",
    hiringFor: ["Product"],
    exampleRole: "Product Manager - Data Solutions",
    careersUrl: "https://boards.greenhouse.io/embed/job_app?token=5596548004",
    sourceLabel: "Greenhouse",
  },
  {
    company: "Reddit",
    hiringFor: ["Product", "Design", "Engineering"],
    exampleRole: "Staff Product Manager, Reddit Answers",
    careersUrl: "https://boards.greenhouse.io/embed/job_app?token=6721235",
    sourceLabel: "Greenhouse",
  },
  {
    company: "Ro",
    hiringFor: ["Product"],
    exampleRole: "Senior Product Manager, Growth",
    careersUrl: "https://jobs.lever.co/ro/f7ca4e67-a6c9-41ae-be25-ad492c576445",
    sourceLabel: "Lever",
  },
  {
    company: "Rockbot",
    hiringFor: ["Design"],
    exampleRole: "Director, Product Design",
    careersUrl: "https://boards.greenhouse.io/embed/job_app?token=5555691004",
    sourceLabel: "Greenhouse",
  },
  {
    company: "Runwise",
    hiringFor: ["Design"],
    exampleRole: "Lead Product Designer",
    careersUrl: "https://boards.greenhouse.io/embed/job_app?token=4600173006",
    sourceLabel: "Greenhouse",
  },
  {
    company: "SeatGeek",
    hiringFor: ["Engineering"],
    exampleRole: "Senior Software Engineer",
    careersUrl: "https://boards.greenhouse.io/embed/job_app?token=7073875",
    sourceLabel: "Greenhouse",
  },
  {
    company: "Shield AI",
    hiringFor: ["Product", "Engineering"],
    exampleRole: "Principal Engineer, Full Stack Developer (R3669)",
    careersUrl: "https://jobs.lever.co/shieldai?department=Hivemind+Special+Division",
    sourceLabel: "Lever",
  },
  {
    company: "SimplePractice",
    hiringFor: ["Design"],
    exampleRole: "Lead Product Designer",
    careersUrl: "https://boards.greenhouse.io/embed/job_app?token=5595275004",
    sourceLabel: "Greenhouse",
  },
  {
    company: "Smile Digital Health",
    hiringFor: ["Product"],
    exampleRole: "Technical Product Manager - Remote United States",
    careersUrl: "https://jobs.lever.co/smiledigitalhealth/e0b80022-4888-48ef-9706-4911d3bc7f5c",
    sourceLabel: "Lever",
  },
  {
    company: "Smartsheet",
    hiringFor: ["Product"],
    exampleRole: "Group Product Manager (Remote Eligible)",
    careersUrl: "https://boards.greenhouse.io/embed/job_app?token=7241244",
    sourceLabel: "Greenhouse",
  },
  {
    company: "SupplyHouse.com",
    hiringFor: ["Product"],
    exampleRole: "Platform Product Manager",
    careersUrl: "https://boards.greenhouse.io/embed/job_app?token=5631342004",
    sourceLabel: "Greenhouse",
  },
  {
    company: "The Athletic",
    hiringFor: ["Design", "Engineering"],
    exampleRole: "Staff Product Designer (Remote)",
    careersUrl: "https://jobs.lever.co/theathletic/ab5ce64b-1f66-4482-b278-04bd39b8bf8a",
    sourceLabel: "Lever",
  },
  {
    company: "Thumbtack",
    hiringFor: ["Design", "Engineering"],
    exampleRole: "Product Designer",
    careersUrl: "https://boards.greenhouse.io/embed/job_app?token=7015101",
    sourceLabel: "Greenhouse",
  },
  {
    company: "Toast",
    hiringFor: ["Product"],
    exampleRole: "Principal Product Manager, Retail POS",
    careersUrl: "https://boards.greenhouse.io/embed/job_app?token=7027999",
    sourceLabel: "Greenhouse",
  },
  {
    company: "Typeform",
    hiringFor: ["Product"],
    exampleRole: "Lead Product Manager",
    careersUrl: "https://boards.greenhouse.io/embed/job_app?token=7095551",
    sourceLabel: "Greenhouse",
  },
  {
    company: "Upstart",
    hiringFor: ["Product"],
    exampleRole: "Principal Product Manager, Conversion",
    careersUrl: "https://boards.greenhouse.io/embed/job_app?token=6821646",
    sourceLabel: "Greenhouse",
  },
  {
    company: "Versapay",
    hiringFor: ["Product", "Engineering"],
    exampleRole: "Principal Payments Product Architect",
    careersUrl: "https://jobs.lever.co/versapay/2432566f-5829-408e-9dd2-f5bf75ab9470",
    sourceLabel: "Lever",
  },
  {
    company: "Viget",
    hiringFor: ["Product", "Design", "Engineering"],
    exampleRole: "Product Manager",
    careersUrl: "https://jobs.lever.co/viget",
    sourceLabel: "Lever",
  },
  {
    company: "Wealth.com",
    hiringFor: ["Design"],
    exampleRole: "Senior Product Designer",
    careersUrl: "https://jobs.lever.co/WealthFinancialTechnologies/01a3542d-23c2-4c97-9c78-0a0fa72d1cfd",
    sourceLabel: "Lever",
  },
];
